# Service account to use for the build
serviceAccount: 'ashu-poc-new@ashu-new-project-445408.iam.gserviceaccount.com'

# Logging options
options:
  logging: CLOUD_LOGGING_ONLY

steps:
  # Step 1: Build a Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/ashu-new-project-445408/ashu-imagenew', '.']

  - name: 'aquasec/trivy'
    args: ['image', '--severity', 'HIGH,CRITICAL', 'gcr.io/ashu-new-project-445408/ashu-imagenew']
    id: 'Run Trivy Scan'
   # Step 3: Create a Docker network
  - name: 'gcr.io/cloud-builders/docker'
    args: ['network', 'create', 'temp-network']
    id: 'Create Docker Network'

  # Step 4: Start a temporary container in that network
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'run', '--rm', '--name', 'temp-container',
      '--network', 'temp-network',
      '-d', '-p', '8080:80',
      'gcr.io/ashu-new-project-445408/ashu-imagenew'
    ]
    id: 'Start Temporary Container'

  # Step 5: Check health endpoint from inside the container
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'exec', 'temp-container', 'curl', '-f', 'http://localhost/health.html'
    ]
    id: 'Health Check'

  # Step 3: Push the Docker image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/ashu-new-project-445408/ashu-imagenew']
