# Service account to use for the build
serviceAccount: 'ashu-poc-new@ashu-new-project-445408.iam.gserviceaccount.com'

# Logging options
options:
  logging: CLOUD_LOGGING_ONLY

steps:
  # Step 1: Build a Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/ashu-new-project-445408/ashu-imagenew', '.']

  # Step 2: Push the Docker image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/ashu-new-project-445408/ashu-imagenew']
