
# Logging options
options:
  logging: CLOUD_LOGGING_ONLY
steps:
  # Step 1: Build a Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/ashu-new-project/ashu-image', '.']
