name: Docker Image CI
on:
  push:
    branches: [ "master1" ]
  pull_request:
    branches: [ "master" ]
jobs:
  build:
    runs-on: windows-latest    # ${{matrix.os}}
    # strategy:
    #   matrix:
    #     os: [ubuntu-latest,windows-latest,macOS-latest]
    steps:
    - name: just single command 
      run: pwd 
    - name: we can run multiple commands 
      run: |
        date
        echo $GITHUB_REF
        echo $TAG
        docker version 
        aws --version 
